apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  labels:
    app: ecommerce-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: ecommerce-backend-container
          image: prasad217/ecommerce-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "mysql-service" # MySQL service name
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Prasad@18"
            - name: DB_NAME
              value: "happy"
            - name: DB_PORT
              value: "3306"
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: EMAIL_PASS
            - name: SESSION_SECRET
              value: "keyboard_cat"
            - name: UPLOADS_PATH
              value: "/uploads"
          volumeMounts:
            - name: uploads-volume
              mountPath: /uploads
      volumes:
        - name: uploads-volume
          hostPath:
            # Updated to the correct path on your host machine
            path: "/Users/prasad/Desktop/ecommerce/local_treasures-root/uploads"
            type: Directory
